name: Build

on:
  push:
    tags:        
      - '**' 

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies (Windows)
      run: |
        sudo apt install gcc-mingw-w64-x86-64
    - name: Create Artifacts Directory
      run: |
        mkdir artifacts
    - name: Build (Windows)
      run: |
        ls
        rustup target add x86_64-pc-windows-gnu
        cargo build --target=x86_64-pc-windows-gnu --release
        cp target/x86_64-pc-windows-gnu/release/cpm.exe artifacts/
    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
          replacesArtifacts: true
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "artifacts/*"
